// BIND9 configuration for Mail-in-a-Docker
options {
    directory "/var/cache/bind";
    dns64-client-break-dnssec yes;
    dns64 64:ff9b::/96 {
        clients { 0.0.0.0/0; ::/0; };
    };
    dns64-server-break-dnssec yes;
    dnssec-validation auto;
    listen-on-v6 { any; };
    listen-on { any; };
    allow-query { any; };
    recursion yes;
    allow-recursion { any; };
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    forward only;
};
